# Travis Continuous Integration script for travis-ci.org

dist: trusty

# Runs all unit tests and check for broken links
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
